apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: smokey-server
  name: smokey-service
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    run: smokey-server
status:
  loadBalancer: {}
